language: objective-c 
osx_image: xcode7.1
xcode_workspace: Silent.xcworkspace
xcode_scheme: Silent

branches:
    only:
        - master

before_script: 
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - pod install

script:
    xctool 
    -workspace Silent.xcworkspace 
    -scheme Silent 
    -destination 'name=iPhone 5,OS=iOS 9.0'
    test 
    -test-sdk iphonesimulator9.1
    -only SilentTests 
    CODE_SIGN_IDENTITY="" 
    CODE_SIGNING_REQUIRED=NO
    # xcodebuild -workspace Silent.xcworkspace -scheme Silent -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' clean test
