language: objective-c 
osx_image: xcode7.1
xcode_workspace: Silent.xcworkspace
xcode_scheme: Silent
xcode_sdk: iphoneos9.1

env:
    matrix:
        - TEST_SDK=iphonesimulator8.4
        - TEST_SDK=iphonesimulator9.1
        - TEST_SDK=iphonesimulator9.2

branches:
    only:
        - master

before_script: 
    - brew update && brew upgrade xctool
    - pod install

script:
    - xctool 
    -workspace Silent.xcworkspace 
    -scheme Silent 
    clean 
    build 
    run-tests 
    -test-sdk $TEST_SDK 
    -targetedDeviceFamily 1,2 
    -only SilentTests 
