language: objective-c 
osx_image: xcode7
xcode_workspace: Silent.xcworkspace
xcode_scheme: Silent

env:
    matrix:
        # - TEST_SDK=iphonesimulator8.4
        - TEST_SDK=iphonesimulator9.1

branches:
    only:
        - master

before_script: 
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - pod install

script:
    xctool 
    -workspace Silent.xcworkspace 
    -scheme Silent 
    -sdk $TEST_SDK 
    test 
    -only SilentTests 
    # xcodebuild -workspace Silent.xcworkspace -scheme Silent -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' clean test
