osx_image: xcode7
sudo: false
language: swift 
# 
# before_install:
#     - gem install cocoapods
#     - pod setup
#     - pod install
# 
xcode_project: Silence.xcworkspace
xcode_project: Silence
xcode_sdk: iphoneos9.1
