language: objective-c 

osx_image: xcode7

before_script: 
    - brew update && brew upgrade xctool
    - pod install

script:
    xctool 
    -workspace Silent.xcworkspace 
    -scheme Silent 
    -sdk iphonesimulator9.0 
    -destination 'platoform=iOS Simulator, name=iPhone 6'
    clean 
    build 
    test
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO

branches:
    only:
        - master

# xcode_project: Silence.xcworkspace
# xcode_project: Silence
# xcode_sdk: iphoneos9.1
