language: objective-c 

osx_image: xcode7

before_script: 
    - brew update && brew upgrade xctool
    - pod install

script:
    - xctool -workspace Silence.xcworkspace -scheme Silence -sdk iphonesimulator clean build test

branches:
    only:
        - master

# xcode_project: Silence.xcworkspace
# xcode_project: Silence
# xcode_sdk: iphoneos9.1
