language: objective-c 
osx_image: xcode7
xcode_workspace: Silent.xcworkspace
xcode_scheme: Silent

env:
    matrix:
        - TEST_SDK=iphonesimulator8.4
        - TEST_SDK=iphonesimulator9.1

branches:
    only:
        - master

before_script: 
    - brew update && brew upgrade xctool
    - pod install

script:
    xctool 
    -workspace Silent.xcworkspace 
    -scheme Silent 
    -sdk $TEST_SDK 
    -targetedDeviceFamily 1,2 
    test 
    -only SilentTests 
